services:
  web:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - /home/vlad/projects/online-shop-gr11/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/html

  php:
    image: vlad/env2
    volumes:
      - ./src/public:/var/www/html

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d