services:
  web:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - /home/vlad/projects/online-shop-gr11/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    image: vlad/env2
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  postgres_db:
    image: postgres:13
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54322:5432"